## Copyright (c) 2022, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: "Protect your cloud resources using a PaloAlto virtual firewall"
stackDescription: "Protect your cloud resources using a PaloAlto virtual firewall"
schemaVersion: 1.1.0
version: "20190404"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - release
  - availability_domain_number

- title: Required Configuration
  visible: true  
  variables:
  - region
  - compartment_ocid
  - availability_domain_name
  - show_advanced

- title: Compute Instances Optional Configuration
  visible: 
      and:
        - show_advanced  
  variables:
  - ssh_public_key
  - instance_os
  - linux_os_version
  - vm_pan_firewall_Shape
  - vm_pan_firewall_FlexShapeOCPUS
  - vm_pan_firewall_FlexShapeMemory
  - vm_pan_firewall_vcn01_priv01_vnic_ip
  - vm_pan_firewall_vcn01_priv02_vnic_ip
  - vm_pan_firewall_vcn01_priv03_vnic_ip
  - vm_pan_firewall_vcn02_priv04_vnic_ip
  - vm_vcn01priv03_Shape
  - vm_vcn01priv03_FlexShapeOCPUS
  - vm_vcn01priv03_FlexShapeMemory
  - vm_vcn01pub02_Shape
  - vm_vcn01pub02_FlexShapeOCPUS
  - vm_vcn01pub02_FlexShapeMemory
  - vm_vcn02priv04_Shape
  - vm_vcn02priv04_FlexShapeOCPUS
  - vm_vcn02priv04_FlexShapeMemory


- title: Network Optional Configuration
  visible: 
      and:
        - show_advanced  
  variables:
  - igw_display_name
  - vcn01_display_name
  - vcn01_dns_label
  - vcn01_cidr_block
  - vcn01_subnet_mgmt_pub01_cidr_block
  - vcn01_subnet_mgmt_pub01_display_name
  - vcn01_subnet_untrusted_pub02_cidr_block
  - vcn01_subnet_untrusted_pub02_display_name
  - vcn01_subnet_trusted_priv03_cidr_block
  - vcn01_subnet_trusted_priv03_display_name
  - vcn02_display_name
  - vcn02_cidr_block
  - vcn02_dns_label
  - vcn02_subnet_trusted_priv04_cidr_block
  - vcn02_subnet_trusted_priv04_display_name

variables:

  # Required Configuration

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: "Compartment"
    description: "Choose Compartment where you want to create the Virtual Machines."
  
  region:
    type: oci:identity:region:name
    required: true
    title: Region
    description: "Choose Region where you want to deploy the resources defined by this stack."

  availability_domain_name:
    type: oci:identity:availabilitydomain:name
    required: true
    visibile: true
    title: "Availability Domain to be chosen"
    description: "Availability Domain to be chosen"
    dependsOn:
      compartmentId: ${compartment_ocid}


  # Optional Configuration

  instance_os:
    type: enum
    required: false
    title: "Instance OS"
    description: "An Operating System that determines the operating system for the instance."
    default: "Oracle Linux"
    enum:
      - "Oracle Linux"
      
  linux_os_version:
    type: enum
    required: false
    title: "Instance OS version"
    description: "An Operating System version that determines the operating system version for the instance."
    default: "8"
    enum:
      - "8"
      - "7.9"

  ssh_public_key:
    type: oci:core:ssh:publickey
    title: "Public SSH Key"
    description: "Choose public SSH Key to be uploaded into compute instances."
    required: false

  vm_pan_firewall_Shape:
    type: oci:core:instanceshape:name
    required: true
    title: "PaloAlto Firewall Server Shape"
    description: "Choose a shape allocated to PaloAlto Firewall Server."
    default: "VM.Standard2.4"
    dependsOn:
      compartmentId: ${compartment_ocid}

  vm_pan_firewall_FlexShapeOCPUS:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "PaloAlto Firewall Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - vm_pan_firewall_Shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - vm_pan_firewall_Shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - vm_pan_firewall_Shape 
            - "VM.Standard.A1.Flex"
          - eq:
            - vm_pan_firewall_Shape 
            - "VM.Optimized3.Flex"

  vm_pan_firewall_FlexShapeMemory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "PaloAlto Firewall Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - vm_pan_firewall_Shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - vm_pan_firewall_Shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - vm_pan_firewall_Shape 
            - "VM.Standard.A1.Flex"
          - eq:
            - vm_pan_firewall_Shape 
            - "VM.Optimized3.Flex"

  vm_pan_firewall_vcn01_priv01_vnic_ip:
    type: string
    required: false
    title: "PaloAlto Firewall Server VCN1 Priv1 VNIC IP"
    description: "PaloAlto Firewall Server VCN1 Priv1 VNIC IP"

  vm_pan_firewall_vcn01_priv02_vnic_ip:
    type: string
    required: false
    title: "PaloAlto Firewall Server VCN1 Priv2 VNIC IP"
    description: "PaloAlto Firewall Server VCN1 Priv2 VNIC IP"

  vm_pan_firewall_vcn01_priv03_vnic_ip:
    type: string
    required: false
    title: "PaloAlto Firewall Server VCN1 Priv3 VNIC IP"
    description: "PaloAlto Firewall Server VCN1 Priv3 VNIC IP"

  vm_pan_firewall_vcn02_priv04_vnic_ip:
    type: string
    required: false
    title: "PaloAlto Firewall Server VCN2 Priv4 VNIC IP"
    description: "PaloAlto Firewall Server VCN2 Priv4 VNIC IP"

  vm_vcn01pub02_Shape:
    type: oci:core:instanceshape:name
    required: true
    title: "vm_vcn01pub2 Server Shape"
    description: "Choose a shape allocated to Frontend Server."
    default: "VM.Standard.E3.Flex"
    dependsOn:
      compartmentId: ${compartment_ocid}

  vm_vcn01pub02_FlexShapeOCPUS:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "vm_vcn01pub2 Server Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - vm_vcn01pub02_Shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - vm_vcn01pub02_Shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - vm_vcn01pub02_Shape 
            - "VM.Standard.A1.Flex"
          - eq:
            - vm_vcn01pub02_Shape 
            - "VM.Optimized3.Flex"

  vm_vcn01pub02_FlexShapeMemory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "vm_vcn01pub2 Server Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - vm_vcn01pub02_Shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - vm_vcn01pub02_Shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - vm_vcn01pub02_Shape 
            - "VM.Standard.A1.Flex"
          - eq:
            - vm_vcn01pub02_Shape 
            - "VM.Optimized3.Flex"

  vm_vcn02priv04_Shape:
    type: oci:core:instanceshape:name
    required: true
    title: "vm_vcn02priv04 Server Shape"
    description: "Choose a shape allocated to Backend Server."
    default: "VM.Standard.E3.Flex"
    dependsOn:
      compartmentId: ${compartment_ocid}

  vm_vcn02priv04_FlexShapeOCPUS:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "vm_vcn02priv04 Server Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - vm_vcn02priv04_Shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - vm_vcn02priv04_Shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - vm_vcn02priv04_Shape 
            - "VM.Standard.A1.Flex"
          - eq:
            - vm_vcn02priv04_Shape 
            - "VM.Optimized3.Flex"

  vm_vcn02priv04_FlexShapeMemory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "vm_vcn02priv04 Server Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - vm_vcn02priv04_Shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - vm_vcn02priv04_Shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - vm_vcn02priv04_Shape 
            - "VM.Standard.A1.Flex"
          - eq:
            - vm_vcn02priv04_Shape 
            - "VM.Optimized3.Flex"

  vm_vcn01priv03_Shape:
    type: oci:core:instanceshape:name
    required: true
    title: "vm_vcn01priv03 Server Shape"
    description: "Choose a shape allocated to vm_vcn01priv03 Server."
    default: "VM.Standard.E3.Flex"
    dependsOn:
      compartmentId: ${compartment_ocid}

  vm_vcn01priv03_FlexShapeOCPUS:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "vm_vcn01priv03 Server Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - vm_vcn01priv03_Shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - vm_vcn01priv03_Shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - vm_vcn01priv03_Shape 
            - "VM.Standard.A1.Flex"
          - eq:
            - vm_vcn01priv03_Shape 
            - "VM.Optimized3.Flex"

  vm_vcn01priv03_FlexShapeMemory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "vm_vcn01priv03 Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - vm_vcn01priv03_Shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - vm_vcn01priv03_Shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - vm_vcn01priv03_Shape 
            - "VM.Standard.A1.Flex"
          - eq:
            - vm_vcn01priv03_Shape 
            - "VM.Optimized3.Flex"

  igw_display_name:
    type: string
    required: false
    title: "IGW Name"
    description: "Type Display name of the Internet Gateway from the VCN."

  vcn01_cidr_block:
    type: string
    required: false
    title: "VCN1 CIDR Block"
    description: "Choose CIDR block that will be assigned to the VCN1."
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"

  vcn01_dns_label:
    type: string
    required: false
    title: "DNS Label of VCN1"
    description: "Type DNS label that will be asigned to the VCN1."

  vcn01_display_name:
    type: string
    required: false
    title: "Name of VCN1"
    description: "Type Display Name assigned to VCN1."

  vcn01_subnet_mgmt_pub01_cidr_block:
    type: string
    required: false
    title: "VCN1's Management Public Subnet CIDR Block"
    description: "Choose CIDR block of the Management Public Subnet in the VCN1."
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"

  vcn01_subnet_mgmt_pub01_display_name:
    type: string
    required: false
    title: "Name of Management Public Subnet in VCN1"
    description: "Type Management Public Subnet Display Name in the VCN1."

  vcn01_subnet_untrusted_pub02_cidr_block:
    type: string
    required: false
    title: "VCN1's Untrusted Public Subnet CIDR Block"
    description: "Choose CIDR block of Untrusted Public Subnet in the VCN1"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"

  vcn01_subnet_untrusted_pub02_display_name:
    type: string
    required: false
    title: "Name of Untrusted Public Subnet in VCN1"
    description: "Type Untrusted Public Subnet Display Name in the VCN1."

  vcn01_subnet_trusted_priv03_cidr_block:
    type: string
    required: false
    title: "VCN1's Trusted Subnet CIDR Block"
    description: "Choose CIDR block of Trusted Subnet in the VCN1"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
  
  vcn01_subnet_trusted_priv03_display_name:
    type: string
    required: false
    title: "Name of Trusted Subnet in VCN1"
    description: "Type Trusted Subnet Display Name in the VCN1."

  vcn02_cidr_block:
    type: string
    required: false
    title: "VCN2 CIDR Block"
    description: "Choose CIDR block that will be assigned to the VCN2."
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
  
  vcn02_dns_label:
    type: string
    required: false
    title: "DNS Label of VCN1"
    description: "Type DNS label that will be asigned to the VCN2."

  vcn02_display_name:
    type: string
    required: false
    title: "Name of VCN2"
    description: "Type Display Name assigned to VCN2."

  vcn02_subnet_trusted_priv04_cidr_block:
    type: string
    required: false
    title: "VCN2's Trusted Subnet CIDR Block"
    description: "Choose CIDR block of Trusted Subnet in the VCN2"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
  
  vcn02_subnet_trusted_priv04_display_name:
    type: string
    required: false
    title: "Name of Trusted Subnet in VCN2"
    description: "Type Trusted Subnet Display Name in the VCN2."

outputs:

  generated_ssh_private_key:
    title: "Generated SSH Private Key"
    displayText: "Generated SSH Private Key"
    type: string
    visible: true